language: php

php:
  - 7.4

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

env:
  global:
    - XDEBUG_MODE=coverage

script:
  - vendor/bin/phpunit --configuration=phpunit.xml --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)